# Generated by Django 5.0 on 2024-01-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_manufacturer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
